[versions]
accompanist = "0.36.0"
appupdate = "2.1.0"
agp = "8.7.1"
androidxlifecycle = "2.9.0-alpha06"
coil3 = "3.0.0"
compose-material-navigation = "1.7.0-beta01"
compose-multiplatform = "1.7.0"
coroutines = "1.9.0"
firebase = "2.1.0"
icons = "1.1.1"
haze = "0.9.0-rc03"
jbadaptive = "1.0.0-rc01"
jblifecycle = "2.8.3"
jbnavigation = "2.8.0-alpha10"
jb-material-navigation = "1.7.0-beta02"
kotlin = "2.0.21"
kotlin-immutable = "0.3.8"
kotlininject = "0.7.2"
ktor = "3.0.0"
media3 = "1.3.1"
mixpanel = "8.0.1"
okhttp = "4.12.0"
readium = "2.4.0"
room = "2.7.0-alpha11"
sqlite = "2.5.0-alpha11"
serialization = "1.7.3"
spotless = "6.25.0"
supabase = "3.0.1"

compileSdk = "35"
minSdk = "24"
targetSdk = "34"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.3.3"
androidx-baselineprofile = "1.3.3"
profileinstaller = "1.4.1"
review = "2.0.2"
junit = "4.13.2"
appcompat = "1.7.0"
material = "1.12.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
buildConfig = "com.github.gmazzo.buildconfig:5.5.0"
cacheFixPlugin = { id = "org.gradle.android.cache-fix", version = "3.0.1" }
androidx-room = { id = "androidx.room", version.ref = "room" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = "com.google.devtools.ksp:2.0.21-1.0.26"
gms-googleServices = "com.google.gms.google-services:4.4.2"
firebase-crashlytics = "com.google.firebase.crashlytics:3.0.2"
spotless = "com.diffplug.spotless:6.25.0"
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidTest = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-baselineprofile" }

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

media = "androidx.media:media:1.7.0"

androidx-activity-compose = "androidx.activity:activity-compose:1.9.3"
androidx-core = "androidx.core:core-ktx:1.15.0"
androidx-documentfile = "androidx.documentfile:documentfile:1.0.1"

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxlifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxlifecycle" }

jetbrains-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jblifecycle" }
jetbrains-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jblifecycle" }
jetbrains-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jbnavigation" }
jetbrains-material-navigation = { module = "org.jetbrains.compose.material:material-navigation", version.ref = "jb-material-navigation" }

lottie-core = "com.airbnb.android:lottie:6.4.0"
lottie-compose = "com.airbnb.android:lottie-compose:6.4.0"

androidx-collection = "androidx.collection:collection:1.4.5"
androidx-palette = "androidx.palette:palette:1.0.0"

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

coil3-coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil3-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil3" }

jetbrains-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "jbadaptive" }
jetbrains-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "jbadaptive" }
jetbrains-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "jbadaptive" }

compose-material-navigation = { module = "androidx.compose.material:material-navigation", version.ref = "compose-material-navigation" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }

google-bom = "com.google.firebase:firebase-bom:33.5.1"
google-analytics = { module = "com.google.firebase:firebase-analytics" }
google-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
google-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
google-admob = "com.google.android.gms:play-services-ads:23.5.0"
google-messaging = { module = "com.google.firebase:firebase-messaging" }
google-playservices-auth = "com.google.android.gms:play-services-auth:21.2.0"
google-remoteConfig = { module = "com.google.firebase:firebase-config" }

google-credentials = "androidx.credentials:credentials:1.3.0"
google-credentials-auth = "androidx.credentials:credentials-play-services-auth:1.3.0"
google-identity = "com.google.android.libraries.identity.googleid:googleid:1.1.1"

google-review = { module = "com.google.android.play:review-ktx", version.ref = "review" }
google-appupdate = { module = "com.google.android.play:app-update-ktx", version.ref = "appupdate" }

firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "firebase" }
firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "firebase" }
firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "firebase" }
firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase" }
firebase-remote-config = { module = "dev.gitlive:firebase-config", version.ref = "firebase" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }

jsoup = "org.jsoup:jsoup:1.17.2"
ksoup = "com.fleeksoft.ksoup:ksoup-lite:0.1.9"

kermit = "co.touchlab:kermit:2.0.4"
kermit-crashlytics = "co.touchlab:kermit-crashlytics:2.0.4"

kotlininject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlininject" }
kotlininject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlininject" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlin-serialization-proto = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable" }

kotlinx-atomicfu = "org.jetbrains.kotlinx:atomicfu:0.26.0"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.1"

ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-defaultheaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }

icons-feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "icons" }
icons-font-awesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "icons" }
icons-tabler = { module = "br.com.devsrsouza.compose.icons:tabler-icons", version.ref = "icons" }
icons-oct = { module = "br.com.devsrsouza.compose.icons:octicons", version.ref = "icons" }
icons-eva = { module = "br.com.devsrsouza.compose.icons:eva-icons", version.ref = "icons" }
icons-line = { module = "br.com.devsrsouza.compose.icons:line-awesome", version.ref = "icons" }

leakCanary = "com.squareup.leakcanary:leakcanary-android:2.14"

markdown-commonmark = { module = "org.commonmark:commonmark", version = "0.23.0" }
markdown-compose = "com.mikepenz:multiplatform-markdown-renderer-m3:0.26.0"
markdown-core = "org.jetbrains:markdown:0.7.3"

media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }

okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

okio = "com.squareup.okio:okio:3.9.1"

openai-kotlin-bom = "com.aallam.openai:openai-client-bom:3.8.2"
openai-client = { module = "com.aallam.openai:openai-client" }

material-kolor = "com.materialkolor:material-kolor:2.0.0"

mixpanel = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel" }

readium-shared = { module = "org.readium.r2:r2-shared", version.ref = "readium" }
readium-streamer = { module = "org.readium.r2:r2-streamer", version.ref = "readium" }
readium-navigator = { module = "org.readium.r2:r2-navigator", version.ref = "readium" }

supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase" }
supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabase-auth-compose = { module = "io.github.jan-tennert.supabase:compose-auth-ui" }
supabase-realtime = { module = "io.github.jan-tennert.supabase:realtime-kt" }
supabase-storage = { module = "io.github.jan-tennert.supabase:storage-kt" }

webview = "io.github.kevinnzou:compose-webview-multiplatform:1.9.20"

threeTenAbp = "com.jakewharton.threetenabp:threetenabp:1.4.4"
dataStore = "androidx.datastore:datastore-preferences:1.1.1"
#todo: remove this. required by remote config kmp
tools-desugarjdklibs = "com.android.tools:desugar_jdk_libs:2.1.2"

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-rules = { group = "androidx.test", name = "rules", version = "1.6.1" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
composeCompiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
