[versions]
accompanist = "0.36.0"
adaptive = "1.0.0"
appupdate = "2.1.0"
agp = "8.6.1"
androidxlifecycle = "2.8.6"
coil = "2.6.0"
compose-alpha = "2024.08.00-alpha02"
compose-bom = "2024.09.03"
compose-material-navigation = "1.7.0-beta01"
compose-multiplatform = "1.6.11"
coroutines = "1.9.0"
firebase = "2.1.0"
icons = "1.0.0"
haze = "0.7.3"
kotlin = "2.0.20"
kotlin-immutable = "0.3.8"
kotlininject = "0.7.2"
ktor = "2.3.12"
material3 = "1.3.0"
media3 = "1.3.1"
mixpanel = "7.0.0"
navigation = "2.8.2"
okhttp = "4.12.0"
pdfviewer = "3.1.0-beta.1"
room = "2.6.1"
serialization = "1.7.3"
spotless = "6.25.0"

compileSdk = "34"
minSdk = "24"
targetSdk = "34"
core-ktx = "1.13.1"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.3.2"
androidx-baselineprofile = "1.3.2"
profileinstaller = "1.4.1"
review = "2.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
cacheFixPlugin = { id = "org.gradle.android.cache-fix", version = "3.0.1" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = "com.google.devtools.ksp:2.0.20-1.0.25"
gms-googleServices = "com.google.gms.google-services:4.4.2"
firebase-crashlytics = "com.google.firebase.crashlytics:3.0.2"
spotless = "com.diffplug.spotless:6.25.0"
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidTest = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-baselineprofile" }

[libraries]
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-web = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }

rebugger = "com.github.theapache64:rebugger:1.0.0-alpha06"
media = "androidx.media:media:1.7.0"
palette = "androidx.palette:palette-ktx:1.0.0"

androidx-activity-compose = "androidx.activity:activity-compose:1.9.2"
androidx-collection = "androidx.collection:collection-ktx:1.4.4"
androidx-core = "androidx.core:core-ktx:1.13.1"
androidx-documentfile = "androidx.documentfile:documentfile:1.0.1"

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxlifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxlifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

lottie-core = "com.airbnb.android:lottie:6.4.0"
lottie-compose = "com.airbnb.android:lottie-compose:6.4.0"

androidx-palette = "androidx.palette:palette:1.0.0"

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
#compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "compose-alpha" }
compose-runtime-runtime = { module = "androidx.compose.runtime:runtime" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended" }
compose-material-material = { module = "androidx.compose.material:material" }
compose-material-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-adaptive-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-android", version.ref = "adaptive" }
androidx-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "adaptive" }
compose-material-navigation = { module = "androidx.compose.material:material-navigation", version.ref = "compose-material-navigation" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-textfonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }

fetch = "com.github.abbas7777:fetch2-android14:3.2.0-beta07"

google-bom = "com.google.firebase:firebase-bom:33.4.0"
google-analytics = { module = "com.google.firebase:firebase-analytics" }
google-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
google-auth = { module = "com.google.firebase:firebase-auth" }
google-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
google-admob = "com.google.android.gms:play-services-ads:23.4.0"
google-firestore = { module = "com.google.firebase:firebase-firestore" }
google-messaging = { module = "com.google.firebase:firebase-messaging" }
google-performance = { module = "com.google.firebase:firebase-perf" }
google-playservices-auth = "com.google.android.gms:play-services-auth:21.2.0"
google-remoteConfig = { module = "com.google.firebase:firebase-config" }

google-review = { module = "com.google.android.play:review-ktx", version.ref = "review" }
google-appupdate = { module = "com.google.android.play:app-update-ktx", version.ref = "appupdate" }

firebase-common = { module = "dev.gitlive:firebase-common", version.ref = "firebase" }
firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "firebase" }
firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase" }
firebase-remote-config = { module = "dev.gitlive:firebase-config", version.ref = "firebase" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }

javax-inject = "javax.inject:javax.inject:1"

kermit = "co.touchlab:kermit:2.0.4"
kermit-crashlytics = "co.touchlab:kermit-crashlytics:2.0.4"

kinject = "com.chrynan.inject:inject:1.2.0"

kotlininject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlininject" }
kotlininject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlininject" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable" }

kotlinx-atomicfu = "org.jetbrains.kotlinx:atomicfu:0.25.0"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.1"

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-defaultheaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }

icons-feather = { module = "br.com.devsrsouza.compose.icons.android:feather", version.ref = "icons" }
icons-font-awesome = { module = "br.com.devsrsouza.compose.icons.android:font-awesome", version.ref = "icons" }
icons-tabler = { module = "br.com.devsrsouza.compose.icons.android:tabler-icons", version.ref = "icons" }

leakCanary = "com.squareup.leakcanary:leakcanary-android:2.14"

markdown-compose = "com.github.jeziellago:compose-markdown:0.5.3"

media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }

okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

openai-kotlin-bom = "com.aallam.openai:openai-client-bom:3.8.2"
openai-client = { module = "com.aallam.openai:openai-client" }

material-kolor = "com.materialkolor:material-kolor:1.7.1"

mixpanel = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel" }

pdfviewer = { module = "com.github.DImuthuUpe:AndroidPdfViewer", version.ref = "pdfviewer" }

threeTenAbp = "com.jakewharton.threetenabp:threetenabp:1.4.4"
timber = "com.jakewharton.timber:timber:5.0.1"
dataStore = "androidx.datastore:datastore-preferences:1.1.1"
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-rules = { group = "androidx.test", name = "rules", version = "1.6.1" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
composeCompiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
